version: '3.8'

services:
  app:
    image: molel/backend-face:latest
    container_name: app
    restart: on-failure
    ports:
      - "8080:80"
    depends_on:
      - db
    env_file:
      - .env

  db:
    image: mongo:latest
    container_name: db
    restart: on-failure
    ports:
      - "27017:27017"
    volumes:
      - ./.database:/data/db
    environment:
      - MONGO_INITDB_DATABASE=${MONGODB_DATABASE_NAME}
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_USER}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD}


  integration:
    build:
      context: .
      dockerfile: integration-test/Dockerfile
    container_name: integration
    image: integration
    env_file:
      - .env
    depends_on:
      - app

