version: '3.8'

services:
  backend-face-service:
    image: molel/backend-face:latest
    container_name: app
    restart: always
    ports:
      - "80:80"
    environment:
      - HTTP_PORT=${HTTP_PORT}
      - MONGODB_DATABASE_NAME=${MONGODB_DATABASE_NAME}
      - MONGODB_USERS_COLLECTION=${MONGODB_USERS_COLLECTION}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PASSWORD=${MONGO_PASSWORD}
