name: ci

on:
  push:
    tags-ignore:
      - v*

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v3
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Lint
        uses: golangci/golangci-lint-action@v3
  test-unittest:
    runs-on: ubuntu-latest
    steps:
      -
        name: Setup Go
        uses: actions/setup-go@v3
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Lint
        uses: golangci/golangci-lint-action@v3
      -
        name: Run unittest
        run: make unittest
  test-integration:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Install golang-migrate
        run: |
          curl -s https://packagecloud.io/install/repositories/golang-migrate/migrate/script.deb.sh | sudo bash
          sudo apt-get update
          sudo apt-get install migrate
      -
        name: Make migrations
        run: |
          cp .env.example .env
          docker-compose up -d mongodb-service
          migrate -path migrations -database "mongodb://user:password@localhost:27017/recognition?authSource=admin" up
          docker-compose stop mongodb-service
      -
        name: Run integration
        run: sudo make integration
  build:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    needs:
      - lint
      - test-unittest
      - test-integration
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout code
        uses: actions/checkout@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      -
        name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      -
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%dT%H-%M-%S')"
      -
        name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: molel/${{ github.event.repository.name }}:${{ steps.date.outputs.date }}
